# fly.toml app configuration file generated for haugscore on 2026-04-17T22:31:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'haugscore'
primary_region = 'fra'

[build]

[env]
  DATA_DIR = '/data'
  NODE_ENV = 'production'
  PORT = '3001'

[[mounts]]
  source = 'haugscore_data'
  destination = '/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/state'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
